// 02-vogue-react/src/App.tsx
import { useState, useEffect } from 'react'
import './App.css'

interface Product {
  id: number
  name: string
  category: string
  price: number
  rating: number
  badge?: string
  image: string
  filter: string[]
  quantity?: number
  description?: string
  materials?: string[]
  details?: string
  images?: string[]
}

interface Category {
  name: string
  description: string
  image: string
}

function App() {
  const [currentFilter, setCurrentFilter] = useState('all')
  const [cart, setCart] = useState<Product[]>([])
  const [cartOpen, setCartOpen] = useState(false)

  // Quick View Modal states
  const [quickViewOpen, setQuickViewOpen] = useState(false)
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null)
  const [selectedImageIndex, setSelectedImageIndex] = useState(0)
  const [activeTab, setActiveTab] = useState('details')

  // Checkout Demo state
  const [showCheckoutDemo, setShowCheckoutDemo] = useState(false)

  const categories: Category[] = [
    {
      name: 'Women',
      description: 'Elegant & Modern',
      image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400&h=500&fit=crop'
    },
    {
      name: 'Men',
      description: 'Classic & Refined',
      image: 'https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?w=400&h=500&fit=crop'
    },
    {
      name: 'Accessories',
      description: 'Complete Your Look',
      image: 'https://images.unsplash.com/photo-1523779917675-b6ed3a42a561?w=400&h=500&fit=crop'
    },
    {
      name: 'Footwear',
      description: 'Step in Style',
      image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=500&fit=crop'
    }
  ]

  const products: Product[] = [
    {
      id: 1,
      name: 'Silk Evening Dress',
      category: 'Women',
      price: 189,
      rating: 5,
      badge: 'new',
      image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=500&fit=crop',
      filter: ['all', 'new', 'popular'],
      description: 'Luxurious silk evening dress featuring a graceful silhouette and timeless elegance. Perfect for gala events and sophisticated occasions.',
      materials: ['100% Mulberry Silk', 'Satin Lining', 'Hidden Zipper'],
      details: 'Size: XS-XL | Dry Clean Only | Made in Italy',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1550928431-ee0ec6db30d3?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1563178406-4cdc2923acbc?w=600&h=600&fit=crop'
      ]
    },
    {
      id: 2,
      name: 'Tailored Blazer',
      category: 'Men',
      price: 249,
      rating: 5,
      image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&h=500&fit=crop',
      filter: ['all', 'popular'],
      description: 'Impeccably crafted blazer with a modern slim fit. Features premium wool construction and refined detailing for the contemporary gentleman.',
      materials: ['Virgin Wool', 'Viscose Lining', 'Mother of Pearl Buttons'],
      details: 'Size: 36-46 | Professional Dry Clean | Handmade in London'
    },
    {
      id: 3,
      name: 'Cashmere Sweater',
      category: 'Women',
      price: 159,
      rating: 4,
      badge: 'sale',
      image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400&h=500&fit=crop',
      filter: ['all', 'sale'],
      description: 'Ultra-soft cashmere sweater offering unparalleled comfort and warmth. A versatile piece that transitions effortlessly from day to evening.',
      materials: ['100% Mongolian Cashmere', 'Ribbed Trim', 'Relaxed Fit'],
      details: 'Size: XS-L | Hand Wash Cold | Made in Scotland'
    },
    {
      id: 4,
      name: 'Leather Handbag',
      category: 'Accessories',
      price: 299,
      rating: 5,
      image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=400&h=500&fit=crop',
      filter: ['all', 'new', 'popular'],
      description: 'Sophisticated leather handbag combining functionality with luxury. Features multiple compartments and signature gold-tone hardware.',
      materials: ['Full Grain Leather', 'Suede Interior', 'Brass Hardware'],
      details: 'Dimensions: 12" x 9" x 4" | Adjustable Strap | Made in Florence'
    },
    {
      id: 5,
      name: 'Classic Trench Coat',
      category: 'Women',
      price: 329,
      rating: 5,
      badge: 'new',
      image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400&h=500&fit=crop',
      filter: ['all', 'new']
    },
    {
      id: 6,
      name: 'Oxford Dress Shoes',
      category: 'Footwear',
      price: 199,
      rating: 4,
      image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400&h=500&fit=crop',
      filter: ['all', 'popular']
    },
    {
      id: 7,
      name: 'Designer Sunglasses',
      category: 'Accessories',
      price: 229,
      rating: 5,
      image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=500&fit=crop',
      filter: ['all', 'new']
    },
    {
      id: 8,
      name: 'Linen Summer Dress',
      category: 'Women',
      price: 139,
      rating: 4,
      badge: 'sale',
      image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&h=500&fit=crop',
      filter: ['all', 'sale']
    },
    {
      id: 9,
      name: 'Slim Fit Jeans',
      category: 'Men',
      price: 119,
      rating: 4,
      image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=500&fit=crop',
      filter: ['all', 'popular']
    },
    {
      id: 10,
      name: 'Ankle Boots',
      category: 'Footwear',
      price: 179,
      rating: 5,
      badge: 'new',
      image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=500&fit=crop',
      filter: ['all', 'new', 'popular']
    },
    {
      id: 11,
      name: 'Wool Scarf',
      category: 'Accessories',
      price: 79,
      rating: 4,
      image: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=500&fit=crop',
      filter: ['all', 'sale']
    },
    {
      id: 12,
      name: 'Formal Shirt',
      category: 'Men',
      price: 89,
      rating: 4,
      image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=500&fit=crop',
      filter: ['all', 'popular']
    }
  ]

  const filters = ['all', 'new', 'sale', 'popular']

  const filteredProducts = products.filter(product =>
    product.filter.includes(currentFilter)
  )

  useEffect(() => {
    const savedCart = localStorage.getItem('vogueCart')
    if (savedCart) {
      setCart(JSON.parse(savedCart))
    }
  }, [])

  useEffect(() => {
    localStorage.setItem('vogueCart', JSON.stringify(cart))
  }, [cart])

  const addToCart = (product: Product) => {
    const existingItem = cart.find(item => item.id === product.id)
    if (existingItem) {
      setCart(cart.map(item =>
        item.id === product.id
          ? { ...item, quantity: (item.quantity || 1) + 1 }
          : item
      ))
    } else {
      setCart([...cart, { ...product, quantity: 1 }])
    }
  }

  const updateQuantity = (product: Product, change: number) => {
    const newQuantity = (product.quantity || 1) + change
    if (newQuantity <= 0) {
      setCart(cart.filter(item => item.id !== product.id))
    } else {
      setCart(cart.map(item =>
        item.id === product.id ? { ...item, quantity: newQuantity } : item
      ))
    }
  }

  const cartItemsCount = cart.reduce((sum, item) => sum + (item.quantity || 1), 0)
  const cartTotal = cart.reduce((sum, item) => sum + item.price * (item.quantity || 1), 0)

  // Quick View Modal Methods
  const openQuickView = (product: Product) => {
    setSelectedProduct(product)
    setSelectedImageIndex(0)
    setActiveTab('details')
    setQuickViewOpen(true)
    document.body.style.overflow = 'hidden'
  }

  const closeQuickView = () => {
    setQuickViewOpen(false)
    setSelectedProduct(null)
    document.body.style.overflow = ''
  }

  const selectImage = (index: number) => {
    setSelectedImageIndex(index)
  }

  const getRelatedProducts = (product: Product) => {
    return products
      .filter(p => p.category === product.category && p.id !== product.id)
      .slice(0, 3)
  }

  // Explore Category Handler
  const exploreCategory = (categoryName: string) => {
    const categoryProducts = products.filter(p => p.category === categoryName)
    if (categoryProducts.length > 0) {
      openQuickView(categoryProducts[0])
    }
  }

  // Checkout Demo Handler
  const handleCheckout = () => {
    setShowCheckoutDemo(true)
    setCartOpen(false)
    document.body.style.overflow = 'hidden'

    // Auto close after 3 seconds
    setTimeout(() => {
      closeCheckoutDemo()
    }, 3000)
  }

  const closeCheckoutDemo = () => {
    setShowCheckoutDemo(false)
    document.body.style.overflow = ''
  }

  return (
    <>
      {/* Navigation */}
      <nav className="navbar">
        <div className="container nav-content">
          <a href="https://jacobsalazar.pages.dev/" className="back-btn">
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none" stroke="currentColor">
              <path d="M15 10H5M5 10L10 5M5 10L10 15" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
            Back to Portfolio
          </a>
          <div className="logo">JAKE'S VAULT</div>
          <div className="nav-links">
            <a href="#home" className="nav-link active">Home</a>
            <a href="#shop" className="nav-link">Shop</a>
            <a href="#about" className="nav-link">About</a>
          </div>
          <div className="nav-actions">
            <button className="icon-btn search-btn" aria-label="Search">
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                <circle cx="11" cy="11" r="8" strokeWidth="2"/>
                <path d="M21 21l-4.35-4.35" strokeWidth="2" strokeLinecap="round"/>
              </svg>
            </button>
            <button className="icon-btn cart-btn" onClick={() => setCartOpen(!cartOpen)} aria-label="Shopping cart">
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                <path d="M9 2L7 8M17 8L15 2M7 8H17M7 8L5 18H19L17 8M10 12V16M14 12V16" strokeWidth="2" strokeLinecap="round"/>
              </svg>
              <span className="cart-count">{cartItemsCount}</span>
            </button>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section id="home" className="hero">
        <div className="container hero-content">
          <div className="hero-text">
            <span className="hero-badge">Exclusive Collection 2025</span>
            <h1 className="hero-title">Where Style Meets Distinction</h1>
            <p className="hero-subtitle">
              Discover Jake's Vault – a curated collection of premium fashion pieces
              for the discerning individual. Timeless elegance, modern sensibility.
            </p>
            <div className="hero-cta">
              <a href="#shop" className="btn btn-primary">Shop Collection</a>
            </div>
          </div>
          <div className="hero-image">
            <img
              src="https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&h=600&fit=crop"
              alt="Fashion model"
              className="hero-img"
            />
          </div>
        </div>
      </section>

      {/* Featured Categories */}
      <section className="categories">
        <div className="container">
          <h2 className="section-title">Shop by Category</h2>
          <div className="categories-grid">
            {categories.map((category, index) => (
              <div key={index} className="category-card">
                <div className="category-image">
                  <img src={category.image} alt={category.name} />
                </div>
                <div className="category-info">
                  <h3>{category.name}</h3>
                  <p>{category.description}</p>
                  <a
                    href="#"
                    className="category-link"
                    onClick={(e) => { e.preventDefault(); exploreCategory(category.name) }}
                  >
                    Explore →
                  </a>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Products Section */}
      <section id="shop" className="products">
        <div className="container">
          <div className="products-header">
            <h2 className="section-title">Featured Products</h2>
            <div className="filters">
              {filters.map(filter => (
                <button
                  key={filter}
                  className={`filter-btn ${currentFilter === filter ? 'active' : ''}`}
                  onClick={() => setCurrentFilter(filter)}
                >
                  {filter}
                </button>
              ))}
            </div>
          </div>

          <div className="products-grid">
            {filteredProducts.map(product => (
              <div key={product.id} className="product-card">
                <div className="product-image">
                  <img src={product.image} alt={product.name} />
                  {product.badge && <span className="product-badge">{product.badge}</span>}
                  <div className="product-actions">
                    <button className="quick-view-btn" onClick={() => openQuickView(product)}>
                      Quick View
                    </button>
                    <button className="add-to-cart-btn" onClick={() => addToCart(product)}>
                      Add to Cart
                    </button>
                  </div>
                </div>
                <div className="product-info">
                  <div className="product-category">{product.category}</div>
                  <h3 className="product-name">{product.name}</h3>
                  <div className="product-price">${product.price}</div>
                  <div className="product-rating">
                    {[1, 2, 3, 4, 5].map(star => (
                      <span key={star} className={`star ${star > product.rating ? 'empty' : ''}`}>
                        ★
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* About Section */}
      <section id="about" className="about">
        <div className="container about-content">
          <div className="about-text">
            <span className="about-badge">Our Philosophy</span>
            <h2 className="about-title">Curated for the Modern Connoisseur</h2>
            <p>
              Jake's Vault is a destination for those who appreciate exceptional style
              and uncompromising quality. Each piece is handpicked to represent the
              perfect fusion of contemporary design and timeless appeal.
            </p>
            <p>
              From refined essentials to bold statement pieces, our collection celebrates
              individuality and sophisticated taste.
            </p>
          </div>
          <div className="about-image">
            <img
              src="https://images.unsplash.com/photo-1558769132-cb1aea1c8573?w=600&h=600&fit=crop"
              alt="Fashion atelier"
            />
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="footer">
        <div className="container footer-content">
          <div className="footer-section">
            <h3 className="logo">JAKE'S VAULT</h3>
            <p>Curated luxury fashion for the discerning individual.</p>
          </div>
          <div className="footer-section">
            <h4>Shop</h4>
            <ul>
              <li><a href="#">New Arrivals</a></li>
              <li><a href="#">Best Sellers</a></li>
              <li><a href="#">Sale</a></li>
            </ul>
          </div>
          <div className="footer-section">
            <h4>Support</h4>
            <ul>
              <li><a href="#">Contact Us</a></li>
              <li><a href="#">Shipping</a></li>
              <li><a href="#">Returns</a></li>
            </ul>
          </div>
        </div>
        <div className="footer-bottom">
          <p>2025 Jake's Vault. Built with React 19 + Vite. Part of Senior Fullstack Developer Portfolio.</p>
        </div>
      </footer>

      {/* Shopping Cart Sidebar */}
      <div className={`cart-sidebar ${cartOpen ? 'active' : ''}`}>
        <div className="cart-header">
          <h3>Shopping Cart</h3>
          <button className="close-cart" onClick={() => setCartOpen(false)}>×</button>
        </div>
        <div className="cart-items">
          {cart.length === 0 ? (
            <p className="empty-cart">Your cart is empty</p>
          ) : (
            cart.map(item => (
              <div key={item.id} className="cart-item">
                <div className="cart-item-image">
                  <img src={item.image} alt={item.name} />
                </div>
                <div className="cart-item-info">
                  <div className="cart-item-name">{item.name}</div>
                  <div className="cart-item-price">${item.price}</div>
                  <div className="cart-item-quantity">
                    <button className="qty-btn" onClick={() => updateQuantity(item, -1)}>−</button>
                    <span>{item.quantity}</span>
                    <button className="qty-btn" onClick={() => updateQuantity(item, 1)}>+</button>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
        <div className="cart-footer">
          <div className="cart-total">
            <span>Total:</span>
            <span className="total-price">${cartTotal}</span>
          </div>
          <button className="btn btn-primary btn-block" onClick={handleCheckout}>Checkout</button>
        </div>
      </div>
      <div className={`cart-overlay ${cartOpen ? 'active' : ''}`} onClick={() => setCartOpen(false)}></div>

      {/* Quick View Modal */}
      {selectedProduct && (
        <>
          <div className={`quick-view-modal ${quickViewOpen ? 'active' : ''}`}>
            <div className="modal-content">
              <button className="modal-close" onClick={closeQuickView}>×</button>

              <div className="modal-body">
                {/* Product Gallery */}
                <div className="product-gallery">
                  <div className="main-image">
                    <img
                      src={selectedProduct.images ? selectedProduct.images[selectedImageIndex] : selectedProduct.image}
                      alt={selectedProduct.name}
                    />
                  </div>
                  {selectedProduct.images && (
                    <div className="thumbnails">
                      {selectedProduct.images.map((img, i) => (
                        <div
                          key={i}
                          className={`thumbnail ${i === selectedImageIndex ? 'active' : ''}`}
                          onClick={() => selectImage(i)}
                        >
                          <img src={img} alt={`${selectedProduct.name} view ${i + 1}`} />
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                {/* Product Details */}
                <div className="product-details">
                  <div className="product-header">
                    <span className="modal-category">{selectedProduct.category}</span>
                    {selectedProduct.badge && <span className="modal-badge">{selectedProduct.badge}</span>}
                  </div>

                  <h2 className="modal-product-name">{selectedProduct.name}</h2>

                  <div className="modal-rating">
                    {[1, 2, 3, 4, 5].map(star => (
                      <span key={star} className={`star ${star > selectedProduct.rating ? 'empty' : ''}`}>★</span>
                    ))}
                    <span className="rating-text">({selectedProduct.rating}.0)</span>
                  </div>

                  <div className="modal-price">${selectedProduct.price}</div>

                  {/* Product Tabs */}
                  <div className="product-tabs">
                    <button
                      className={`tab-btn ${activeTab === 'details' ? 'active' : ''}`}
                      onClick={() => setActiveTab('details')}
                    >
                      Details
                    </button>
                    <button
                      className={`tab-btn ${activeTab === 'materials' ? 'active' : ''}`}
                      onClick={() => setActiveTab('materials')}
                    >
                      Materials
                    </button>
                    <button
                      className={`tab-btn ${activeTab === 'shipping' ? 'active' : ''}`}
                      onClick={() => setActiveTab('shipping')}
                    >
                      Shipping
                    </button>
                  </div>

                  <div className="tab-content">
                    {activeTab === 'details' && (
                      <div className="tab-pane">
                        <p>{selectedProduct.description || 'Premium fashion piece designed with exceptional attention to detail and quality.'}</p>
                        {selectedProduct.details && <p className="details-info">{selectedProduct.details}</p>}
                      </div>
                    )}
                    {activeTab === 'materials' && (
                      <div className="tab-pane">
                        {selectedProduct.materials ? (
                          <ul>
                            {selectedProduct.materials.map((material, i) => (
                              <li key={i}>{material}</li>
                            ))}
                          </ul>
                        ) : (
                          <p>Crafted from premium materials selected for quality and sustainability.</p>
                        )}
                      </div>
                    )}
                    {activeTab === 'shipping' && (
                      <div className="tab-pane">
                        <p>Free express shipping on orders over $150. Standard delivery 3-5 business days. International shipping available.</p>
                      </div>
                    )}
                  </div>

                  {/* Add to Cart Section */}
                  <div className="modal-actions">
                    <div className="quantity-selector">
                      <button className="qty-btn">−</button>
                      <input type="number" defaultValue="1" min="1" max="10" />
                      <button className="qty-btn">+</button>
                    </div>
                    <button className="btn-add-to-cart" onClick={() => { addToCart(selectedProduct); closeQuickView() }}>
                      Add to Cart - ${selectedProduct.price}
                    </button>
                  </div>

                  {/* Related Products */}
                  {getRelatedProducts(selectedProduct).length > 0 && (
                    <div className="related-products">
                      <h3>You might also like</h3>
                      <div className="related-grid">
                        {getRelatedProducts(selectedProduct).map(related => (
                          <div key={related.id} className="related-item" onClick={() => openQuickView(related)}>
                            <img src={related.image} alt={related.name} />
                            <div className="related-info">
                              <h4>{related.name}</h4>
                              <span>${related.price}</span>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
          <div className={`quick-view-overlay ${quickViewOpen ? 'active' : ''}`} onClick={closeQuickView}></div>
        </>
      )}

      {/* Checkout Demo Modal */}
      <div className={`checkout-demo-modal ${showCheckoutDemo ? 'active' : ''}`}>
        <div className="checkout-demo-content">
          <div className="checkout-icon">
            <svg width="80" height="80" viewBox="0 0 80 80" fill="none">
              <circle cx="40" cy="40" r="38" stroke="#10b981" strokeWidth="4" strokeLinecap="round" strokeDasharray="0.5 4"/>
              <path d="M25 40L35 50L55 30" stroke="#10b981" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </div>
          <h2 className="checkout-title">Thanks for checking out!</h2>
          <p className="checkout-message">
            This is a demo portfolio project showcasing React 19 with Vite and modern ecommerce design.
            No actual orders are processed.
          </p>
          <div className="checkout-footer">
            <p>Created by Jacob Salazar</p>
            <button className="btn-close-demo" onClick={closeCheckoutDemo}>Got it!</button>
          </div>
        </div>
      </div>
      <div className={`checkout-demo-overlay ${showCheckoutDemo ? 'active' : ''}`} onClick={closeCheckoutDemo}></div>
    </>
  )
}

export default App

// 01-kura-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';

interface Product {
  id: number;
  name: string;
  category: string;
  price: number;
  rating: number;
  badge?: string;
  image: string;
  filter: string[];
  quantity?: number;
  description?: string;
  materials?: string[];
  dimensions?: string;
  images?: string[];
}

interface Category {
  name: string;
  description: string;
  image: string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'Kura - Scandinavian Furniture Store';

  cartOpen = false;
  cart: Product[] = [];
  currentFilter = 'all';
  filters = ['all', 'new', 'sale', 'popular'];

  // Quick View Modal states
  quickViewOpen = false;
  selectedProduct: Product | null = null;
  selectedImageIndex = 0;
  activeTab = 'details';

  // Checkout Demo state
  showCheckoutDemo = false;

  categories: Category[] = [
    {
      name: 'Seating',
      description: 'Chairs & Sofas',
      image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop'
    },
    {
      name: 'Tables',
      description: 'Dining & Coffee',
      image: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=400&h=300&fit=crop'
    },
    {
      name: 'Storage',
      description: 'Shelves & Cabinets',
      image: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&h=300&fit=crop'
    },
    {
      name: 'Lighting',
      description: 'Lamps & Fixtures',
      image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=400&h=300&fit=crop'
    }
  ];

  products: Product[] = [
    {
      id: 1,
      name: 'Minimal Oak Chair',
      category: 'Seating',
      price: 349,
      rating: 5,
      badge: 'new',
      image: 'https://images.unsplash.com/photo-1503602642458-232111445657?w=400&h=500&fit=crop',
      filter: ['all', 'new', 'popular'],
      description: 'Crafted from solid oak with a minimalist design that combines comfort with timeless Scandinavian aesthetics. Perfect for dining rooms or as an accent piece.',
      materials: ['Solid Oak Wood', 'Natural Oil Finish', 'Steel Reinforcements'],
      dimensions: 'W: 18" × D: 20" × H: 32"',
      images: [
        'https://images.unsplash.com/photo-1503602642458-232111445657?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1549497538-303791108f95?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600&h=600&fit=crop'
      ]
    },
    {
      id: 2,
      name: 'Nordic Dining Table',
      category: 'Tables',
      price: 899,
      rating: 5,
      image: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=400&h=500&fit=crop',
      filter: ['all', 'popular'],
      description: 'Spacious dining table featuring clean lines and a natural wood finish. Seats up to 6 people comfortably, ideal for family gatherings.',
      materials: ['Solid Pine Wood', 'Water-based Lacquer', 'Metal Brackets'],
      dimensions: 'W: 72" × D: 36" × H: 30"',
      images: [
        'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&h=600&fit=crop'
      ]
    },
    {
      id: 3,
      name: 'Ash Wood Bookshelf',
      category: 'Storage',
      price: 549,
      rating: 4,
      image: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=400&h=500&fit=crop',
      filter: ['all']
    },
    {
      id: 4,
      name: 'Pendant Light Fixture',
      category: 'Lighting',
      price: 199,
      rating: 5,
      badge: 'sale',
      image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=400&h=500&fit=crop',
      filter: ['all', 'sale']
    },
    {
      id: 5,
      name: 'Lounge Armchair',
      category: 'Seating',
      price: 649,
      rating: 5,
      badge: 'new',
      image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=400&h=500&fit=crop',
      filter: ['all', 'new', 'popular']
    },
    {
      id: 6,
      name: 'Coffee Table Round',
      category: 'Tables',
      price: 449,
      rating: 4,
      image: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=400&h=500&fit=crop',
      filter: ['all', 'popular']
    },
    {
      id: 7,
      name: 'Modular Cabinet System',
      category: 'Storage',
      price: 799,
      rating: 5,
      badge: 'new',
      image: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&h=500&fit=crop',
      filter: ['all', 'new']
    },
    {
      id: 8,
      name: 'Arc Floor Lamp',
      category: 'Lighting',
      price: 299,
      rating: 4,
      badge: 'sale',
      image: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=400&h=500&fit=crop',
      filter: ['all', 'sale']
    },
    {
      id: 9,
      name: 'Velvet Sofa 3-Seater',
      category: 'Seating',
      price: 1299,
      rating: 5,
      image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=500&fit=crop',
      filter: ['all', 'popular']
    },
    {
      id: 10,
      name: 'Walnut Side Table',
      category: 'Tables',
      price: 249,
      rating: 4,
      badge: 'sale',
      image: 'https://images.unsplash.com/photo-1550254478-ead40cc54513?w=400&h=500&fit=crop',
      filter: ['all', 'sale']
    },
    {
      id: 11,
      name: 'Wall-Mounted Shelf',
      category: 'Storage',
      price: 179,
      rating: 4,
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=500&fit=crop',
      filter: ['all']
    },
    {
      id: 12,
      name: 'Table Lamp Set',
      category: 'Lighting',
      price: 149,
      rating: 5,
      badge: 'new',
      image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=500&fit=crop',
      filter: ['all', 'new', 'popular']
    }
  ];

  get filteredProducts(): Product[] {
    return this.products.filter(product =>
      product.filter.includes(this.currentFilter)
    );
  }

  get cartItemsCount(): number {
    return this.cart.reduce((sum, item) => sum + (item.quantity || 0), 0);
  }

  get cartTotal(): number {
    return this.cart.reduce((sum, item) =>
      sum + (item.price * (item.quantity || 0)), 0
    );
  }

  setFilter(filter: string): void {
    this.currentFilter = filter;
  }

  toggleCart(): void {
    this.cartOpen = !this.cartOpen;
  }

  addToCart(product: Product): void {
    const existingItem = this.cart.find(item => item.id === product.id);

    if (existingItem) {
      existingItem.quantity = (existingItem.quantity || 0) + 1;
    } else {
      this.cart.push({ ...product, quantity: 1 });
    }

    this.saveCart();
  }

  updateQuantity(item: Product, change: number): void {
    const cartItem = this.cart.find(i => i.id === item.id);
    if (!cartItem) return;

    cartItem.quantity = (cartItem.quantity || 0) + change;

    if (cartItem.quantity <= 0) {
      this.cart = this.cart.filter(i => i.id !== item.id);
    }

    this.saveCart();
  }

  private saveCart(): void {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('kuraCart', JSON.stringify(this.cart));
    }
  }

  private loadCart(): void {
    if (typeof localStorage !== 'undefined') {
      const savedCart = localStorage.getItem('kuraCart');
      if (savedCart) {
        this.cart = JSON.parse(savedCart);
      }
    }
  }

  ngOnInit(): void {
    this.loadCart();
  }

  // Quick View Modal Methods
  openQuickView(product: Product): void {
    this.selectedProduct = product;
    this.selectedImageIndex = 0;
    this.activeTab = 'details';
    this.quickViewOpen = true;
    document.body.style.overflow = 'hidden';
  }

  closeQuickView(): void {
    this.quickViewOpen = false;
    this.selectedProduct = null;
    document.body.style.overflow = '';
  }

  selectImage(index: number): void {
    this.selectedImageIndex = index;
  }

  setActiveTab(tab: string): void {
    this.activeTab = tab;
  }

  getRelatedProducts(product: Product): Product[] {
    return this.products
      .filter(p => p.category === product.category && p.id !== product.id)
      .slice(0, 3);
  }

  getProductsByCategory(categoryName: string): Product[] {
    return this.products.filter(p => p.category === categoryName);
  }

  // Enhanced category exploration
  exploreCategory(categoryName: string): void {
    const categoryProducts = this.getProductsByCategory(categoryName);
    if (categoryProducts.length > 0) {
      this.openQuickView(categoryProducts[0]);
    }
  }

  // Checkout Demo Handler
  handleCheckout(): void {
    this.showCheckoutDemo = true;
    this.cartOpen = false;
    document.body.style.overflow = 'hidden';

    // Auto close after 3 seconds
    setTimeout(() => {
      this.closeCheckoutDemo();
    }, 3000);
  }

  closeCheckoutDemo(): void {
    this.showCheckoutDemo = false;
    document.body.style.overflow = '';
  }
}

<!-- Navigation -->
<nav class="navbar">
    <div class="container nav-content">
        <a href="https://jacobsalazar.pages.dev/" class="back-btn">
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none" stroke="currentColor">
                <path d="M15 10H5M5 10L10 5M5 10L10 15" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            Back to Portfolio
        </a>
        <div class="logo">KURA</div>
        <div class="nav-links">
            <a href="#home" class="nav-link active">Home</a>
            <a href="#shop" class="nav-link">Shop</a>
            <a href="#about" class="nav-link">About</a>
        </div>
        <div class="nav-actions">
            <button class="icon-btn search-btn" aria-label="Search">
                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                    <circle cx="11" cy="11" r="8" stroke-width="2"/>
                    <path d="M21 21l-4.35-4.35" stroke-width="2" stroke-linecap="round"/>
                </svg>
            </button>
            <button class="icon-btn cart-btn" (click)="toggleCart()" aria-label="Shopping cart">
                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                    <path d="M9 2L7 8M17 8L15 2M7 8H17M7 8L5 18H19L17 8M10 12V16M14 12V16" stroke-width="2" stroke-linecap="round"/>
                </svg>
                <span class="cart-count">{{ cartItemsCount }}</span>
            </button>
        </div>
    </div>
</nav>

<!-- Hero Section -->
<section id="home" class="hero">
    <div class="container hero-content">
        <div class="hero-text">
            <span class="hero-badge">New Collection 2025</span>
            <h1 class="hero-title">Timeless Design for Modern Living</h1>
            <p class="hero-subtitle">
                Discover our curated collection of Scandinavian-inspired furniture
                that combines minimalist aesthetics with functional elegance.
            </p>
            <div class="hero-cta">
                <a href="#shop" class="btn btn-primary">Explore Collection</a>
            </div>
        </div>
        <div class="hero-image">
            <img src="https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop"
                 alt="Modern Scandinavian furniture" class="hero-img">
        </div>
    </div>
</section>

<!-- Featured Categories -->
<section class="categories">
    <div class="container">
        <h2 class="section-title">Shop by Category</h2>
        <div class="categories-grid">
            <div class="category-card" *ngFor="let category of categories">
                <div class="category-image">
                    <img [src]="category.image" [alt]="category.name">
                </div>
                <div class="category-info">
                    <h3>{{ category.name }}</h3>
                    <p>{{ category.description }}</p>
                    <a (click)="exploreCategory(category.name); $event.preventDefault()"
                       href="#"
                       class="category-link">Explore →</a>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Products Section -->
<section id="shop" class="products">
    <div class="container">
        <div class="products-header">
            <h2 class="section-title">Featured Products</h2>
            <div class="filters">
                <button class="filter-btn"
                        [class.active]="currentFilter === filter"
                        *ngFor="let filter of filters"
                        (click)="setFilter(filter)">
                    {{ filter }}
                </button>
            </div>
        </div>

        <div class="products-grid">
            <div class="product-card" *ngFor="let product of filteredProducts">
                <div class="product-image">
                    <img [src]="product.image" [alt]="product.name">
                    <span class="product-badge" *ngIf="product.badge">{{ product.badge }}</span>
                    <div class="product-actions">
                        <button class="quick-view-btn" (click)="openQuickView(product)">
                            Quick View
                        </button>
                        <button class="add-to-cart-btn" (click)="addToCart(product)">
                            Add to Cart
                        </button>
                    </div>
                </div>
                <div class="product-info">
                    <div class="product-category">{{ product.category }}</div>
                    <h3 class="product-name">{{ product.name }}</h3>
                    <div class="product-price">${{ product.price }}</div>
                    <div class="product-rating">
                        <span class="star" *ngFor="let star of [1,2,3,4,5]"
                              [class.empty]="star > product.rating">★</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- About Section -->
<section id="about" class="about">
    <div class="container about-content">
        <div class="about-text">
            <span class="about-badge">Our Philosophy</span>
            <h2 class="about-title">Designed for Life, Crafted to Last</h2>
            <p>
                At Kura, we believe furniture should be more than just functional.
                Each piece is thoughtfully designed to enhance your living space while
                standing the test of time.
            </p>
            <p>
                Our Scandinavian-inspired collection embodies the principles of
                minimalism, sustainability, and timeless beauty.
            </p>
        </div>
        <div class="about-image">
            <img src="https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&h=600&fit=crop"
                 alt="Craftsmanship">
        </div>
    </div>
</section>

<!-- Footer -->
<footer class="footer">
    <div class="container footer-content">
        <div class="footer-section">
            <h3 class="logo">KURA</h3>
            <p>Timeless Scandinavian design for modern living.</p>
        </div>
        <div class="footer-section">
            <h4>Shop</h4>
            <ul>
                <li><a href="#">New Arrivals</a></li>
                <li><a href="#">Best Sellers</a></li>
                <li><a href="#">Sale</a></li>
            </ul>
        </div>
        <div class="footer-section">
            <h4>Support</h4>
            <ul>
                <li><a href="#">Contact Us</a></li>
                <li><a href="#">Shipping</a></li>
                <li><a href="#">Returns</a></li>
            </ul>
        </div>
    </div>
    <div class="footer-bottom">
        <p>2025 Kura Furniture. Built with Angular 17. Part of Senior Fullstack Developer Portfolio.</p>
    </div>
</footer>

<!-- Shopping Cart Sidebar -->
<div class="cart-sidebar" [class.active]="cartOpen">
    <div class="cart-header">
        <h3>Shopping Cart</h3>
        <button class="close-cart" (click)="toggleCart()">×</button>
    </div>
    <div class="cart-items">
        <p class="empty-cart" *ngIf="cart.length === 0">Your cart is empty</p>
        <div class="cart-item" *ngFor="let item of cart">
            <div class="cart-item-image">
                <img [src]="item.image" [alt]="item.name">
            </div>
            <div class="cart-item-info">
                <div class="cart-item-name">{{ item.name }}</div>
                <div class="cart-item-price">${{ item.price }}</div>
                <div class="cart-item-quantity">
                    <button class="qty-btn" (click)="updateQuantity(item, -1)">−</button>
                    <span>{{ item.quantity }}</span>
                    <button class="qty-btn" (click)="updateQuantity(item, 1)">+</button>
                </div>
            </div>
        </div>
    </div>
    <div class="cart-footer">
        <div class="cart-total">
            <span>Total:</span>
            <span class="total-price">${{ cartTotal }}</span>
        </div>
        <button class="btn btn-primary btn-block" (click)="handleCheckout()">Checkout</button>
    </div>
</div>
<div class="cart-overlay" [class.active]="cartOpen" (click)="toggleCart()"></div>

<!-- Quick View Modal -->
<div class="quick-view-modal" [class.active]="quickViewOpen" *ngIf="selectedProduct">
    <div class="modal-content">
        <button class="modal-close" (click)="closeQuickView()">×</button>

        <div class="modal-body">
            <!-- Product Gallery -->
            <div class="product-gallery">
                <div class="main-image">
                    <img [src]="selectedProduct.images ? selectedProduct.images[selectedImageIndex] : selectedProduct.image"
                         [alt]="selectedProduct.name">
                </div>
                <div class="thumbnails" *ngIf="selectedProduct.images">
                    <div class="thumbnail"
                         *ngFor="let img of selectedProduct.images; let i = index"
                         [class.active]="i === selectedImageIndex"
                         (click)="selectImage(i)">
                        <img [src]="img" [alt]="selectedProduct.name + ' view ' + (i+1)">
                    </div>
                </div>
            </div>

            <!-- Product Details -->
            <div class="product-details">
                <div class="product-header">
                    <span class="modal-category">{{ selectedProduct.category }}</span>
                    <span class="modal-badge" *ngIf="selectedProduct.badge">{{ selectedProduct.badge }}</span>
                </div>

                <h2 class="modal-product-name">{{ selectedProduct.name }}</h2>

                <div class="modal-rating">
                    <span class="star" *ngFor="let star of [1,2,3,4,5]"
                          [class.empty]="star > selectedProduct.rating">★</span>
                    <span class="rating-text">({{ selectedProduct.rating }}.0)</span>
                </div>

                <div class="modal-price">${{ selectedProduct.price }}</div>

                <!-- Product Tabs -->
                <div class="product-tabs">
                    <button class="tab-btn"
                            [class.active]="activeTab === 'details'"
                            (click)="setActiveTab('details')">Details</button>
                    <button class="tab-btn"
                            [class.active]="activeTab === 'materials'"
                            (click)="setActiveTab('materials')">Materials</button>
                    <button class="tab-btn"
                            [class.active]="activeTab === 'dimensions'"
                            (click)="setActiveTab('dimensions')">Dimensions</button>
                </div>

                <div class="tab-content">
                    <div class="tab-pane" *ngIf="activeTab === 'details'">
                        <p>{{ selectedProduct.description || 'Elegant furniture piece designed with Scandinavian minimalism in mind. Combines functionality with timeless aesthetics.' }}</p>
                    </div>
                    <div class="tab-pane" *ngIf="activeTab === 'materials'">
                        <ul *ngIf="selectedProduct.materials">
                            <li *ngFor="let material of selectedProduct.materials">{{ material }}</li>
                        </ul>
                        <p *ngIf="!selectedProduct.materials">Premium materials selected for durability and sustainability.</p>
                    </div>
                    <div class="tab-pane" *ngIf="activeTab === 'dimensions'">
                        <p>{{ selectedProduct.dimensions || 'Please contact us for detailed dimensions.' }}</p>
                    </div>
                </div>

                <!-- Add to Cart Section -->
                <div class="modal-actions">
                    <div class="quantity-selector">
                        <button class="qty-btn">−</button>
                        <input type="number" value="1" min="1" max="10">
                        <button class="qty-btn">+</button>
                    </div>
                    <button class="btn-add-to-cart" (click)="addToCart(selectedProduct); closeQuickView()">
                        Add to Cart - ${{ selectedProduct.price }}
                    </button>
                </div>

                <!-- Related Products -->
                <div class="related-products" *ngIf="getRelatedProducts(selectedProduct).length > 0">
                    <h3>You might also like</h3>
                    <div class="related-grid">
                        <div class="related-item"
                             *ngFor="let related of getRelatedProducts(selectedProduct)"
                             (click)="openQuickView(related)">
                            <img [src]="related.image" [alt]="related.name">
                            <div class="related-info">
                                <h4>{{ related.name }}</h4>
                                <span>${{ related.price }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="quick-view-overlay" [class.active]="quickViewOpen" (click)="closeQuickView()"></div>

<!-- Checkout Demo Modal -->
<div class="checkout-demo-modal" [class.active]="showCheckoutDemo">
    <div class="checkout-demo-content">
        <div class="checkout-icon">
            <svg width="80" height="80" viewBox="0 0 80 80" fill="none">
                <circle cx="40" cy="40" r="38" stroke="#10b981" stroke-width="4" stroke-linecap="round" stroke-dasharray="0.5 4"/>
                <path d="M25 40L35 50L55 30" stroke="#10b981" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
        </div>
        <h2 class="checkout-title">Thanks for checking out!</h2>
        <p class="checkout-message">
            This is a demo portfolio project showcasing Angular 17 and modern ecommerce design.
            No actual orders are processed.
        </p>
        <div class="checkout-footer">
            <p>Created by Jacob Salazar</p>
            <button class="btn-close-demo" (click)="closeCheckoutDemo()">Got it!</button>
        </div>
    </div>
</div>
<div class="checkout-demo-overlay" [class.active]="showCheckoutDemo" (click)="closeCheckoutDemo()"></div>
